version: "3.9"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: "mydb"
      POSTGRES_USER: "karim"
      POSTGRES_PASSWORD: "pipidorka"
    ports:
      - "5432:5432"